In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("world_population.csv")

In [4]:
df.info

<bound method DataFrame.info of      Rank CCA3            Country           Capital Continent  \
0      36  AFG        Afghanistan             Kabul      Asia
1     138  ALB            Albania            Tirana    Europe
2      34  DZA            Algeria           Algiers    Africa
3     213  ASM     American Samoa         Pago Pago   Oceania
4     203  AND            Andorra  Andorra la Vella    Europe
..    ...  ...                ...               ...       ...
229   226  WLF  Wallis and Futuna          Mata-Utu   Oceania
230   172  ESH     Western Sahara          El Aaiún    Africa
231    46  YEM              Yemen             Sanaa      Asia
232    63  ZMB             Zambia            Lusaka    Africa
233    74  ZWE           Zimbabwe            Harare    Africa

     2022 Population  2020 Population  2015 Population  2010 Population  \
0         41128771.0       38972230.0       33753499.0       28189672.0
1          2842321.0        2866849.0        2882481.0        2913399.0
2         44903225.0       43451666.0       39543154.0       35856344.0
3            44273.0          46189.0          51368.0          54849.0
4            79824.0          77700.0          71746.0          71519.0
..               ...              ...              ...              ...
229          11572.0          11655.0          12182.0          13142.0
230         575986.0         556048.0         491824.0         413296.0
231       33696614.0       32284046.0       28516545.0       24743946.0
232       20017675.0       18927715.0              NaN       13792086.0
233       16320537.0       15669666.0       14154937.0       12839771.0

     2000 Population  1990 Population  1980 Population  1970 Population  \
0         19542982.0       10694796.0       12486631.0       10752971.0
1          3182021.0        3295066.0        2941651.0        2324731.0
2         30774621.0       25518074.0       18739378.0       13795915.0
3            58230.0          47818.0          32886.0          27075.0
4            66097.0          53569.0          35611.0          19860.0
..               ...              ...              ...              ...
229          14723.0          13454.0          11315.0           9377.0
230         270375.0         178529.0         116775.0          76371.0
231       18628700.0       13375121.0        9204938.0        6843607.0
232        9891136.0        7686401.0        5720438.0        4281671.0
233       11834676.0       10113893.0        7049926.0        5202918.0

     Area (km²)  Density (per km²)  Growth Rate  World Population Percentage
0      652230.0            63.0587       1.0257                         0.52
1       28748.0            98.8702       0.9957                         0.04
2     2381741.0            18.8531       1.0164                         0.56
3         199.0           222.4774       0.9831                         0.00
4         468.0           170.5641       1.0100                         0.00
..          ...                ...          ...                          ...
229       142.0            81.4930       0.9953                         0.00
230    266000.0             2.1654       1.0184                         0.01
231    527968.0            63.8232       1.0217                         0.42
232    752612.0            26.5976       1.0280                         0.25
233    390757.0            41.7665       1.0204                         0.20

[234 rows x 17 columns]>

In [5]:
df.shape

(234, 17)

In [7]:
df.head(5)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [8]:
df.tail(5)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [16]:
df['Continent']

0         Asia
1       Europe
2       Africa
3      Oceania
4       Europe
        ...
229    Oceania
230     Africa
231       Asia
232     Africa
233     Africa
Name: Continent, Length: 234, dtype: object

In [17]:
df.iloc[0]

Rank                                    36
CCA3                                   AFG
Country                        Afghanistan
Capital                              Kabul
Continent                             Asia
2022 Population                 41128771.0
2020 Population                 38972230.0
2015 Population                 33753499.0
2010 Population                 28189672.0
2000 Population                 19542982.0
1990 Population                 10694796.0
1980 Population                 12486631.0
1970 Population                 10752971.0
Area (km²)                        652230.0
Density (per km²)                  63.0587
Growth Rate                         1.0257
World Population Percentage           0.52
Name: 0, dtype: object

In [19]:
df.describe()

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
count,234.000000,2.300000e+02,2.330000e+02,2.300000e+02,2.270000e+02,2.270000e+02,2.290000e+02,2.290000e+02,2.300000e+02,2.320000e+02,230.000000,232.000000,234.000000
mean,117.500000,3.463225e+07,3.360071e+07,3.206600e+07,3.027016e+07,2.684050e+07,1.933046e+07,1.628288e+07,1.586650e+07,5.816637e+05,456.811652,1.009553,0.427051
std,67.694165,1.378892e+08,1.358732e+08,1.315071e+08,1.260742e+08,1.133525e+08,8.130962e+07,6.934547e+07,6.835586e+07,1.769133e+06,2083.740364,0.013390,1.714977
min,1.000000,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,7.330000e+02,7.520000e+02,1.000000e+00,0.026100,0.912000,0.000000
25%,59.250000,4.197385e+05,4.064710e+05,3.942950e+05,3.827265e+05,3.294700e+05,2.619280e+05,2.237520e+05,1.458805e+05,2.567250e+03,36.598125,1.001925,0.010000
50%,117.500000,5.762857e+06,5.456681e+06,5.244415e+06,4.889741e+06,4.491202e+06,3.785847e+06,3.135123e+06,2.511718e+06,7.714100e+04,95.346750,1.007900,0.070000
75%,175.750000,2.265372e+07,2.152263e+07,1.973085e+07,1.682585e+07,1.562547e+07,1.188276e+07,9.817257e+06,8.817329e+06,4.146432e+05,236.884000,1.016650,0.280000
max,234.000000,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,9.823725e+08,8.225344e+08,1.709824e+07,23172.266700,1.069100,17.880000

In [20]:
df.isnull().sum()

Rank                           0
CCA3                           0
Country                        0
Capital                        0
Continent                      0
2022 Population                4
2020 Population                1
2015 Population                4
2010 Population                7
2000 Population                7
1990 Population                5
1980 Population                5
1970 Population                4
Area (km²)                     2
Density (per km²)              4
Growth Rate                    2
World Population Percentage    0
dtype: int64

In [30]:
df.sort_values(by="World Population Percentage",ascending = False).head(10)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60

In [32]:
df[df['Continent'].str.contains('Oceania')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
11,55,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33
44,223,COK,Cook Islands,Avarua,Oceania,17011.0,17029.0,17695.0,17212.0,15897.0,17123.0,17651.0,20470.0,236.0,72.0805,1.0005,0.00
66,162,FJI,Fiji,Suva,Oceania,929766.0,920422.0,917200.0,905169.0,832509.0,780430.0,644582.0,527634.0,18272.0,50.8847,1.0056,0.01
70,183,PYF,French Polynesia,Papeete,Oceania,306279.0,301920.0,291787.0,283788.0,250927.0,211089.0,163591.0,117891.0,4167.0,73.5011,1.0074,0.00
81,191,GUM,Guam,Hagåtña,Oceania,171774.0,169231.0,167978.0,164905.0,160188.0,138263.0,110286.0,88300.0,549.0,312.8852,1.0073,0.00
107,192,KIR,Kiribati,Tarawa,Oceania,131232.0,126463.0,116707.0,107995.0,88826.0,75124.0,60813.0,57437.0,811.0,161.8150,1.0183,0.00
126,215,MHL,Marshall Islands,Majuro,Oceania,41569.0,43413.0,49410.0,53416.0,54224.0,46047.0,31988.0,23969.0,181.0,229.6630,0.9886,0.00
132,194,FSM,Micronesia,Palikir,Oceania,114164.0,112106.0,109462.0,107588.0,111709.0,98603.0,76299.0,58989.0,702.0,162.6268,1.0091,0.00
142,225,NRU,Nauru,Yaren,Oceania,12668.0,12315.0,11185.0,10241.0,10377.0,9598.0,7635.0,6663.0,21.0,603.2381,1.0125,0.00
145,185,NCL,New Caledonia,Nouméa,Oceania,289950.0,286403.0,283032.0,261426.0,221537.0,177264.0,148599.0,110982.0,18575.0,15.6097,1.0075,0.00
146,123,NZL,New Zealand,Wellington,Oceania,5185288.0,5061133.0,4590590.0,4346338.0,3855266.0,3397389.0,3147168.0,2824061.0,270467.0,19.1716,1.0108,0.07
150,232,NIU,Niue,Alofi,Oceania,1934.0,1942.0,1847.0,1812.0,2074.0,2533.0,3637.0,5185.0,260.0,7.4385,0.9985,0.00
153,210,NFK,Northern Mariana Islands,Saipan,Oceania,49551.0,49587.0,51514.0,54087.0,80338.0,48002.0,17613.0,10143.0,464.0,106.7909,1.0014,0.00
157,222,PLW,Palau,Ngerulmud,Oceania,NaN,17972.0,17794.0,18540.0,19726.0,15293.0,12252.0,11366.0,459.0,39.3355,1.0017,0.00
160,93,PNG,Papua New Guinea,Port Moresby,Oceania,10142619.0,9749640.0,8682174.0,7583269.0,5508297.0,3864972.0,3104788.0,2489059.0,462840.0,21.9139,1.0194,0.13
179,188,WSM,Samoa,Apia,Oceania,222382.0,214929.0,203571.0,194672.0,184008.0,168186.0,164905.0,142771.0,2842.0,78.2484,1.0165,0.00
191,166,SLB,Solomon Islands,Honiara,Oceania,724273.0,691191.0,612660.0,540394.0,429978.0,324171.0,233668.0,172833.0,28896.0,25.0648,1.0232,0.01
209,233,TKL,Tokelau,Nukunonu,Oceania,1871.0,1827.0,1454.0,1367.0,1666.0,1669.0,1647.0,1714.0,12.0,155.9167,1.0119,0.00
210,197,TON,Tonga,Nuku‘alofa,Oceania,106858.0,105254.0,106122.0,107383.0,102603.0,98727.0,96708.0,86484.0,747.0,143.0495,1.0079,0.00
216,227,TUV,Tuvalu,Funafuti,Oceania,11312.0,11069.0,10877.0,10550.0,9638.0,9182.0,7731.0,5814.0,26.0,435.0769,1.0096,0.00
225,181,VUT,Vanuatu,Port-Vila,Oceania,326740.0,311685.0,276438.0,245453.0,192074.0,150882.0,118156.0,87019.0,12189.0,26.8061,1.0238,0.00
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00

In [33]:
df.columns

Index(['Rank', 'CCA3', 'Country', 'Capital', 'Continent', '2022 Population',
       '2020 Population', '2015 Population', '2010 Population',
       '2000 Population', '1990 Population', '1980 Population',
       '1970 Population', 'Area (km²)', 'Density (per km²)', 'Growth Rate',
       'World Population Percentage'],
      dtype='object')

In [34]:
df.groupby('Continent').mean(numeric_only=True)

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,
Africa,92.157895,2.545588e+07,2.387144e+07,2.141970e+07,1.889820e+07,1.459837e+07,1.137696e+07,8.586032e+06,6.567175e+06,5.378793e+05,126.406569,1.021180,0.313509
Asia,77.560000,9.632739e+07,9.495513e+07,8.916500e+07,8.908777e+07,8.058084e+07,4.864000e+07,4.027833e+07,4.383988e+07,6.427628e+05,1025.024136,1.009384,1.183800
Europe,124.500000,1.505537e+07,1.491584e+07,1.502745e+07,1.471228e+07,1.481769e+07,1.478520e+07,1.420000e+07,1.311848e+07,4.602082e+05,663.324742,1.002256,0.186600
North America,160.925000,1.500740e+07,1.485591e+07,1.425960e+07,1.356802e+07,1.215174e+07,1.053166e+07,9.207334e+06,7.885865e+06,6.061044e+05,272.494118,1.004285,0.187750
Oceania,188.521739,2.046386e+06,1.910149e+06,1.756664e+06,1.613164e+06,1.357512e+06,1.162775e+06,9.965322e+05,8.469683e+05,3.702209e+05,132.543065,1.007383,0.023913
South America,97.571429,3.120119e+07,3.082357e+07,2.950960e+07,2.678940e+07,2.501589e+07,2.122474e+07,1.727064e+07,1.378194e+07,1.301303e+06,20.971979,1.007957,0.391429